services:
  redis:
    container_name: todoapp-redis
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: todoapp-backend

    env_file:
      - .env

    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis

  worker:
    build: .
    container_name: todoapp-worker
    command: celery -A core worker -l INFO
    env_file:
      - .env
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend

  beat:
    build: .
    container_name: todoapp-beat
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: on-failure
    ports:
      # Change the number before : to the port the web interface should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '143:143'
      # Change the number before : to the port the POP3 server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '110:110'
    volumes:
      # This is where smtp4dev stores the database..
        - smtp4dev-data:/smtp4dev
    environment:
      #Specifies the URLs the web UI will use inside the container.
      - ServerOptions__Urls=http://*:80

      #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
      - ServerOptions__HostName=smtp4dev
volumes:
  smtp4dev-data: