services:
  redis:
    container_name: todoapp-redis
    image: redis
    restart: on-failure
    command: redis-server --save 60 1 --loglevel warning

  postgres:
    image: postgres:16
    container_name: todoapp-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: .
    container_name: todoapp-backend

    env_file:
      - .env

    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media

    command: gunicorn core.wsgi --bind 0.0.0.0:8000

    depends_on:
      - redis
      - postgres

  worker:
    build: .
    container_name: todoapp-worker
    command: celery -A core worker -l INFO
    env_file:
      - .env
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend

  beat:
    build: .
    container_name: todoapp-beat
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend

  nginx:
    image: nginx
    container_name: todoapp-nginx
    restart: always

    ports:
      - "80:80"

    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media

volumes:

  static_volume:
  postgres_data:
  media_volume: